#!/usr/bin/bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repo="origin"
FORCE=true
git_object=$1

if [ -z $git_object ];then
  echo "can not remove git object {${git_object}}, do not exists"
fi

if [ x${FORCE} != x'true' ];then
    read -p "please confirm your clean objects files ${git_object} [y/n]" options
if [ x$options != x'y' ];then
    exit
fi
fi

set -ex
git filter-branch --force --index-filter "git rm -rf --cached --ignore-unmatch ${git_object}" --prune-empty --tag-name-filter cat -- --all

rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --prune=now
