#!/usr/bin/env bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
WORK_DIR=`pwd`
GCC_PROJECT=gcc-project

if [ -z $1 ];then
    echo ""
    read -p "use default work directory : ${WORK_DIR} [y/n]" options
    if [ x$options != x'y' ];then
        exit -1
    fi
else
    WORK_DIR=$1
fi

#GCC_REPO="git@github.com:gcc-mirror/gcc.git"
GCC_REPO=git@gitlab.alibaba-inc.com:zhongxiao.yzx/gcc-project.git
GCC_PROJ_NAME=${GCC_REPO##*/}
GCC_PROJ_NAME=${GCC_PROJ_NAME%\.*}

GCC_DIR=${WORK_DIR}/${GCC_PROJECT}

echo "try to sync projects :"
echo "GCC_REPO    : ${GCC_REPO}"
echo "GCC_DIR     : ${GCC_DIR}"

set -x
if [ ! -d ${GCC_DIR} ];then
    git clone ${GCC_REPO} ${GCC_DIR} --recursive --progress
else
    cd ${GCC_DIR}
    git pull origin master
    git submodule sync --recursive
    git submodule update --recursive
fi
set +x
