#!/usr/bin/env bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
DEV_HOME=~/Workspace/Server

# default options 
ACTION_FORCE=false

OPT_HOST=10.248.171.5
OPT_PORT=22
OPT_USER=yaozhongxiao
OPT_HOST_HOME=/home/${OPT_USER}/workspace
OPT_MountPoint=dev

function usage() {
    cat << EOF
    Usage: $0 [options]
    Options:
        --help            This Message.
        -p|--port         Set the remote server port.
        -h|--host         Set the remote server ip or hostname.
        -u|--user         Set the User to launch in remote server.
        -m|--mount-point  Set the Mount Point.
EOF
}

function options_parse() {
    while test $# -gt 0; do
        case "$1" in
            -h|--host)
                shift
                if [ x"$1" != x"-*" ];then
                    OPT_HOST=$1
                fi
                ;;
            -p|--port)
                shift
                if [ x"$1" != x"-*" ];then
                    OPT_PORT=$1
                fi
                ;;
            -u|--user)
                shift
                if [ x"$1" != x"-*" ];then
                    OPT_USER=$1
                fi
                ;;
            -m|--mount-point)
                shift
                if [ x"$1" != x"-*" ];then
                    OPT_MountPoint=$1
                fi
                ;;
            -*)
                usage
                exit 1
                ;;
            *)
                COMMANDS+=($1)
                ;;
        esac
        shift
    done
}

# options parsing
echo $0 $@
options_parse $@

if [ ! -d ${DEV_HOME}/${OPT_MountPoint} ];then
    mkdir -p ${DEV_HOME}/${OPT_MountPoint}
fi
set -x
sshfs -p ${OPT_PORT} ${OPT_USER}@${OPT_HOST}:${OPT_HOST_HOME}  ${DEV_HOME}/${OPT_MountPoint}
set +x

echo "$0 complete...."
