#!/usr/bin/env bash
#
# Copyright 2021 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
script_dir="$(cd "$(dirname "$0")"; pwd -P)"

function usage() {
  cat << EOF
  Usage: $0 [options]   ; android device runner (adrun)
  Options:
      --help          this message
      --list          list android devices infos
      --start  avd    start avd(emulator)
EOF
}

function installEmulator() {
  ${script_dir}/emu_setup.sh install
}

function ShowAndroidDevices() {
  avd_list=($(emulator -list-avds))
  avd_nums=${#avd_list[@]}
  echo "----------${avd_nums} avd ------------"
  emulator -list-avds

  devices_list=($(adb devices | grep "device$" | awk '{print $1}'))
  devices_nums=${#devices_list[@]}
  echo "\n----------${devices_nums} connnected devices ------------"
  adb devices
}

function StartAVD() {
  avd_name=$1
  ${script_dir}/emu_bootup.sh --verbose
}

function ConnectDevices() {
  # $(adb shell getprop sys.boot_completed)
  echo ""
}

COMMANDS=()
function options_parse() {
  while test $# -gt 0; do
      case "$1" in
          -l|--list)
            ShowAndroidDevices
            ;;
          --start)
            shift
            if [ x"$1" != x"-*" ];then
              StartAVD $1
            fi
            ;;
          *)
            usage
            ;;
      esac
      shift
  done
}
echo $0 $@
options_parse $@

