#!/usr/bin/env bash
#
# Copyright 2022 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LLVM_HOME="/usr/local/opt/llvm@12/" 
WASM_LD="${LLVM_HOME}/bin/wasm-ld" 

if [ ! -f ${WASM_LD} -a ! -L ${WASM_LD} ];then
  echo "#brew install llvm@12"
fi

cat <<EOF
==> llvm@12
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm@12/lib -Wl,-rpath,/usr/local/opt/llvm@12/lib"

llvm@12 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have llvm@12 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/llvm@12/bin:\$PATH"' >> /Users/zhongxiao.yzx/.bash_profile

For compilers to find llvm@12 you may need to set:
  export LDFLAGS="-L/usr/local/opt/llvm@12/lib"
  export CPPFLAGS="-I/usr/local/opt/llvm@12/include"
EOF

export PATH="${LLVM_HOME}/bin:$PATH"
export LDFLAGS="-L${LLVM_HOME}/lib ${LDFLAGS}"
export CPPFLAGS="-I${LLVM_HOME}/include ${CPPFLAGS}"

