#!/usr/bin/env bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
SPEC_ROOT=/cpp/zhongxiao.yzx/speccpu2017

function usage() {
    cat << EOF
    Usage: $0 [options]
    Options:
        -h|--help         This Message.
        --spec            Set The Spec Testing Root Directory
EOF
}

function options_parse() {
    while test $# -gt 0; do
        case "$1" in
            --spec)
                shift
                if [ x"$1" != x"-*" ];then
                    SPEC_ROOT=$1
                fi
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option \"$1\"." >&2
                usage
                exit 1
                ;;
        esac
        shift
    done
}

# options parsing
echo $0 $@
options_parse $@

WORK_DIR=${SPEC_ROOT}
set -x
if [ ! -f ${WORK_DIR}/cli_run.sh ];then
    echo "invalid command options !"
    usage
    exit -1
fi

set -x
# clean specs
cd ${WORK_DIR}

git reset HEAD --hard
git clean -f
git reset HEAD --hard
git clean -f
rm -rf benchspec*
rm -rf result*
rm -rf bin/lib/
rm -rf config/
