#!/usr/bin/env bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"

# TODO() : try to reset the compiler and spec root by users
LLVM_COMPILER=/cpp/zhongxiao.yzx/compiler/llvm-release
SPEC_ROOT="$(readlink -f $(pwd))"

ACTION_FORCE=false

# default command
OPT_ITERATIONS=1
# COMMANDS=(541.leela_r)
# COMMANDS=(531.deepsjeng_r)
# COMMANDS=(502.gcc_r)
# COMMANDS=(intspeed)
# COMMANDS=(intrate)
# COMMANDS=(523.xalancbmk_r)

COMMANDS=(intrate)

function usage() {
    cat << EOF
    Usage: $0 [options]
    Options:
        -h|--help         This Message.
        --llvm            Set The LLVM Compiler Root Directory.
        --spec            Set The Spec Testing Root Directory
        -f|--force        Force Run.
        -i|--iterations   Set The Spec Testing Iterations
EOF
}

function options_parse() {
    while test $# -gt 0; do
        case "$1" in
            --llvm)
                shift
                if [ x"$1" != x"-*" ];then
                    LLVM_COMPILER=$1
                fi
                ;;
            -i|--iterations)
                shift
                if [ x"$1" != x"-*" ];then
                    OPT_ITERATIONS=$1
                fi
                ;;
            --spec)
                shift
                if [ x"$1" != x"-*" ];then
                    SPEC_ROOT=$1
                fi
                ;;
            -f|--force)
                ACTION_FORCE=true
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            -*)
                echo "Unknown option \"$1\"." >&2
                usage
                exit 1
                ;;
            *)
                COMMANDS+=($1)
                ;;
        esac
        shift
    done
}

# options parsing
echo $0 $@
options_parse $@

WORK_DIR=${SPEC_ROOT}
if [ ! -f ${WORK_DIR}/cli_run.sh ];then
    echo "can not find cli_run.sh in workspace [${WORK_DIR}]!"
    usage
    exit -1
fi

read -p "please confirm your compiler : ${LLVM_COMPILER} [y/n]" options
if [ x$options != x'y' ];then
    exit
fi

set -x
# run test cases
cd ${WORK_DIR}
echo `pwd`
sh cli_run.sh --cc llvm --cc-root ${LLVM_COMPILER} "--iterations=${OPT_ITERATIONS}" ${COMMANDS[@]}

# **DO NOT** need to backup benchspec, bcz,
# the output is configured in *.cfg so that
# "llvm --- *_mytest-m64"
# "gcc  --- *_mytest-64"
#
# BENCHSPEC=benchspec
# BENCHSPEC_LLVM=benchspec-llvm
# if [ -d ${BENCHSPEC_LLVM} ];then
#     rm -rf ${BENCHSPEC_LLVM}
# fi
# cp -r ${BENCHSPEC} ${BENCHSPEC_LLVM}

# save the test result
BENCHSPEC_RESULT=result
BENCHSPEC_RESULT_LLVM=result-llvm-$(date +%Y%m%d-%H%M%S)
if [ -d ${BENCHSPEC_RESULT_LLVM} ];then
    rm -rf ${BENCHSPEC_RESULT_LLVM}
fi
cp -r ${BENCHSPEC_RESULT} ${BENCHSPEC_RESULT_LLVM}
