#!/usr/bin/env bash
#
# Copyright 2021 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
WORKSPACE_DIR=`pwd`

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
CLI_DIR=${SCRIPT_DIR}/..
GN_TEMPLATE_DIR=${SCRIPT_DIR}/gn-template

source ${CLI_DIR}/env.sh

if [ -f ${WORKSPACE_DIR}/.gn -o x"${WORKSPACE_DIR}" = x"${GN_TEMPLATE_DIR}" ];then
    read -p "${WORKSPACE_DIR}/.gn exists, do you really want to init [y/n]?" options
    if [ x"y" != x${options} ];then
        exit
    fi
    rm -rf ${WORKSPACE_DIR}/.gn
fi

yes|cp -Rf ${GN_TEMPLATE_DIR}/. ${WORKSPACE_DIR}/

echo "gn-init complete ..."
