#!/usr/bin/env bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
CURRENT_DIR=`pwd`
SRC_FILE=""
TARGET_FILE=""

function usage() {
    cat << EOF
    Usage: $0 [options]
    Options:
    -h|--help         This Message.
    -f|--force        Force Building.
    -o                set the output file
EOF
}

function options_parse() {
    while test $# -gt 0; do
        case "$1" in
            -o)
              shift
              if [ x"$1" != x"-*" ];then
                TARGET_FILE=$1
              fi
              ;;
            -f|--force)
                BUILD_FORCE=true
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                SRC_FILE=$1
                ;;
        esac
        shift
    done
}

# parse cli options
echo $0 $@
options_parse $@

if [ -z ${SRC_FILE} ];then
    echo "source file missed, please check the input *.ll exists!"
    exit 1
fi

echo "opt --dot-callgraph ${SRC_FILE}"
opt --dot-callgraph ${SRC_FILE} >/dev/null

dot -Tpng ${SRC_FILE}.callgraph.dot -o cg.${SRC_FILE}.png

