#!/usr/bin/env bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e
SCRIPT_DIR=$(cd $(dirname $0); pwd -P)
ROOT_DIR=`pwd`
if [ -z $1 ];then
    echo ""
    read -p "use default work directory : ${ROOT_DIR} [y/n]" options
    if [ x$options != x'y' ];then
        exit
    fi
else
    ROOT_DIR=$1
fi

function install_prerequisition() {
    # install prerequisition utils
    sudo yum install -y lbzip2 flex flex-devel file -b current

    local option=$1
    echo "download_prerequisition $@"
    case $option in
        1)  echo "install from the gcc sources"
            cd ${GCC_SRC_ROOT}
            base_url_mirror=http://ftp.tsukuba.wide.ad.jp/software/gcc/infrastructure
            sed -i -e "/^base_url=/a\
                base_url='${base_url_mirror}'" -e "s/^base_url=/#&/" ./contrib/download_prerequisites
            sh ./contrib/download_prerequisites
            ;;
        2)  echo 'install from http://ftp.tsukuba.wide.ad.jp/software/gcc/infrastructure'
            cd ${GCC_SRC_ROOT}
            # install from sources
            if [ -f gmp-6.1.0.tar.bz2 -a -f mpfr-3.1.4.tar.bz2 -a -f mpc-1.0.3.tar.gz -f isl-0.18.tar.bz2];then
                return;
            fi
            base_url="http://ftp.tsukuba.wide.ad.jp/software/gcc/infrastructure/"
            wget ${base_url}/gmp-6.1.0.tar.bz2
            wget ${base_url}/mpfr-3.1.4.tar.bz2
            wget ${base_url}/mpc-1.0.3.tar.gz
            wget ${base_url}/isl-0.18.tar.bz2
            ;;
        3)  echo 'install with yum installer'
            sudo yum install -y gmp gmp-devel mpfr mpfr-devel libmpc libmpc-devel -b current
            ;;
        *)  echo 'download nothing for prerequisition'
            ;;
    esac
}

INSTALL_ROOT=${ROOT_DIR}/gcc-release
GCC_SRC_ROOT=${ROOT_DIR}/gcc-project
GCC_OBJ_ROOT=${ROOT_DIR}/gcc-build
if [ ! -d ${GCC_OBJ_ROOT} ];then
    mkdir -p ${GCC_OBJ_ROOT}
fi
GCC_INSTALL_PREFIX=${INSTALL_ROOT}

set -x
# 1. download prerequisition
if [ ! -d ${GCC_INSTALL_PREFIX} ];then
    echo "gcc building prerequisites downloading ..."
    install_prerequisition 3
fi

# 2. config
cd ${GCC_OBJ_ROOT}
# rebuild will failed bcz of the CC has changed previous run
# by bootstrap, we need to clean the previous config beforehand!
if [ -f ${GCC_OBJ_ROOT}/gcc/config.cache ];then
    make distclean
fi
${GCC_SRC_ROOT}/configure --prefix=${GCC_INSTALL_PREFIX} -enable-checking=release -enable-languages=c,c++ -disable-multilib
set +x

echo "${GCC_SRC_ROOT} building ..."
make -j64

echo "${GCC_SRC_ROOT} installing ..."
make install

# 4. config the gcc and libstdc++.* to available
cp -rf ${SCRIPT_DIR}/gcc-enable ${GCC_INSTALL_PREFIX}/gcc-enable
sed -i "s:\(GCC_RELEASE=\).*:\1${GCC_INSTALL_PREFIX}:g" ${GCC_INSTALL_PREFIX}/gcc-enable
# echo "source ${GCC_INSTALL_PREFIX}/gcc-enable" >> ~/.bashrc

echo "~_~"
echo "gcc building complete ..."
