#!/usr/bin/env bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
WORK_DIR=`pwd`
LLVM_PROJECT=llvm-project

if [ -z $1 ];then
    echo ""
    read -p "use default work directory : ${WORK_DIR} [y/n]" options
    if [ x$options != x'y' ];then
        exit -1
    fi
else
    WORK_DIR=$1
fi

# LLVM_REPO="git@github.com:llvm/llvm-project.git"
# upstream syncing is slow, use the inner mirror
LLVM_REPO="git@gitlab.alibaba-inc.com:zhongxiao.yzx/llvm-project.git"
LLVM_PROJ_NAME=${LLVM_REPO##*/}
LLVM_PROJ_NAME=${LLVM_PROJ_NAME%\.*}

LLVM_DIR=${WORK_DIR}/${LLVM_PROJECT}

echo "try to sync projects :"
echo "LLVM_REPO    : ${LLVM_REPO}"
echo "LLVM_DIR     : ${LLVM_DIR}"

set -x
if [ ! -d ${LLVM_DIR} ];then
    git clone ${LLVM_REPO} ${LLVM_DIR} --recursive --progress
else
    cd ${LLVM_DIR}
    git pull origin master
    git submodule sync --recursive
    git submodule update --recursive
fi
set +x
