#!/usr/bin/env bash
#
# Copyright 2020 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
ROOT_DIR=`pwd`
LLVM_BUILD="llvm-build"

ENABLE_NINJA=false # false
BUILD_TYPE=Debug
BUILD_FORCE=false

function usage() {
    cat << EOF
    Usage: $0 [options]
    Options:
    -h|--help         This Message.
    -f|--force        Force Building.
    --ninja           Build With ninja (default is makefile)
    --build           LLVM Project to be built
    -d|--debug        Build With Debug Mode (default)
    -r|--release      Build With Release Mode
EOF
}

function options_parse() {
    while test $# -gt 0; do
        case "$1" in
            --build)
              shift
              if [ x"$1" != x"-*" ];then
                LLVM_BUILD=$1
              fi
              ;;
            --ninja)
                ENABLE_NINJA=true
                ;;
            -f|--force)
                BUILD_FORCE=true
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
            echo "Unknown option \"$1\"." >&2
                usage
                exit 1
                ;;
        esac
        shift
    done
}

# parse cli options
echo $0 $@
options_parse $@

LLVM_OBJ_ROOT=${ROOT_DIR}/${LLVM_BUILD}

if [ x"false" == x"${BUILD_FORCE}" ];then
if [ -z $1 ];then
    echo ""
    read -p "use default work directory : ${LLVM_OBJ_ROOT} [y/n]" options
    if [ x$options != x'y' ];then
        exit
    fi
fi
fi


echo "SCRIPT_DIR   : ${SCRIPT_DIR}"
echo "ROOT_DIR     : ${ROOT_DIR}"
echo "ENABLE_NINJA : ${ENABLE_NINJA}"
echo "current dir  : `pwd`"

set -x
cd ${LLVM_OBJ_ROOT}
# https://llvm.org/docs/TestingGuide.html
make -j64 check-llvm check-clang check-lld check-cxxabi check-cxx check-clang-tools
# make -j64 check-llvm

echo "~_~"
echo "llvm testing complete ..."
