#!/usr/bin/env bash
#
# Copyright 2023 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR="$(cd "$(dirname $0)"; pwd -P)"

if [ -z "${V8_HOME}" ];then
  echo "please set V8_HOME before-hand!"
  exit -1
fi

d8=`which d8`

function usage() {
    cat << EOF
    Usage: $0 [options] *.js
    Options:
    -h|--help         This Message.
    -f|--force        Force Building.
EOF
}

SRC_FILE=""
DEFAULT_OPT="--trace-turbo --trace-opt --trace-deopt"
D8_OPT="--allow-natives-syntax"

function options_parse() {
    while test $# -gt 0; do
        case "$1" in
            -f|--force)
                BUILD_FORCE=true
                ;;
            -h|--help)
              usage
              exit 0
              ;;
            --*)
              D8_OPT="${D8_OPT} $1"
              ;;
            *)
              SRC_FILE=$1
              ;;
        esac
        shift
    done
}

# parse cli options
echo $0 $@
options_parse $@

if [ ! -f "${SRC_FILE}" ];then
  echo "can not find file ${SRC_FILE}"
  exit -1
fi

set -x
${d8} $D8_OPT ${SRC_FILE}