#!/usr/bin/env bash
#
# Copyright 2023 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ******************************************************************
# the detailed process refers to the following links
#   https://shakti.org.in/learn_with_shakti/c-debugging-gdb.html
#   https://github.com/riscv-software-src/riscv-isa-sim
#

set -e
rdb_root="$(cd "$(dirname "$0")"; pwd -P)"

function usage() {
    cat << EOF
    Usage: $0 [options] app.elf
    Options:
      restart        restart debugger
      -h|--help      show help
EOF
}

function restart() {
  echo "gpkill spike"
  gpkill spike
  echo "gpkill openocd"
  gpkill openocd
  exit 0
}

function options_parse() {
    while test $# -gt 0; do
        case "$1" in
            restart)
              restart
              ;;
            -h|--help)
              ${rdb_root}/rdbserver -h
              ;;
        esac
        shift
    done
}

# parse options
echo $0 $@
options_parse $@

# 1. start the rdbserver
${rdb_root}/rdbserver $@ &

# 2. start the rdbclient
${rdb_root}/rdbclient $@