#!/usr/bin/env bash
#
# Copyright 2023 WorkGroup Participants. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
script_dir="$(cd "$(dirname "$0")"; pwd -P)"
riscv_root=${script_dir}

ld_script=${riscv_root}/template/spike.lds
start_asm=${riscv_root}/template/start.S
declare -a args=()
cc=riscv64-unknown-elf-gcc

function usage() {
    cat << EOF
    Usage: $0 [options] $@
    Options:
      --lds       script.lds   set the linker-script
      -s|--start  start.S      set the start.S
      -h|--help                show help
EOF
}

function options_parse() {
    while test $# -gt 0; do
        case "$1" in
            --lds)
              if [[ ! -z $2 ]] && [[ $2 != -* ]];then
                ld_script=$2
                shift
              fi
                ;;
            -s|--start)
              if [[ ! -z $2 ]] && [[ $2 != -* ]];then
                start_asm=$2
                shift
              fi
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                args+=("$1")
                ;;
        esac
        shift
    done
}

# parse options
echo $0 $@
options_parse $@

set -x
$cc -T ${ld_script} -nostartfiles ${start_asm} ${args[@]}